name: coatl-dev-pr-create
description: GitHub Action to create Pull Request using gh.
author: cesarcoatl

inputs:
  gh-token:
    description: >-
      GitHub token.
    required: true
  title:
    description: >-
      Title for the pull request.
    required: false
    default: ''
  body:
    description: >-
      Body for the pull request.
    required: false
    default: ''
  body-file:
    description: >-
      Read body text from file.
    required: false
    default: ''
  auto-merge:
    description: >-
      Automatically merge only after necessary requirements are met.
    required: false
    default: 'yes'
  delete-branch:
    description: >-
      Delete the local and remote branch after merge.
    required: false
    default: 'yes'

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Create Pull Request
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_BODY_FILE: ${{ inputs.body-file }}
        INPUT_AUTO_MERGE: ${{ inputs.auto-merge }}
        INPUT_DELETE_BRANCH: ${{ inputs:delete-branch }}
      run: |
        create.sh
