version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: "github-actions"
    directory: "/pre-commit-autoupdate"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    commit-message:
      prefix: "refactor"
