---
commitizen:
  gpg_sign: true
  ignored_tag_formats:
  - v$major
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 5.1.6
  version_files:
  - README.md
  version_scheme: semver
