---
commitizen:
  gpg_sign: true
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.2.0
  version_files:
  - README.md
  version_scheme: semver
