name: coatl-dev-pip-compile
description: Run pip-compile to upgrade your Python 2/3 requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      A file or location of the requirement file(s).
    required: true
  python-version:
    description: >-
      Python version to use for installing pip-tools.
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build ${{ github.action_path }} \
          --build-arg VERSION=${{ inputs.python-version }} \
          --file ${{ github.action_path }}/Dockerfile \
          --tag coatl-pip-compile:${{ inputs.python-version }}

    - shell: bash
      run: |
        docker run --rm \
          --env "INPUT_PATH=${{ inputs.path }}" \
          --volume ${{ github.workspace }}://github/workspace \
          coatl-pip-compile:${{ inputs.python-version }}
