name: coatl-dev-pip-compile
description: Run pip-compile to upgrade your Python 2/3 requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      A file or location of the requirement file(s).
    required: true
  working-directory:
    description: >-
      Useful when the path input is a file inside a directory.
    required: false
    default: '.'
  python-version:
    description: >-
      Python version to use for installing pip-tools.
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build ${{ github.action_path }} \
          --build-arg VERSION=${{ inputs.python-version }} \
          --file ${{ github.action_path }}/Dockerfile \
          --tag coatl-pip-compile:${{ inputs.python-version }}

    - shell: bash
      id: check-working-directory
      run: |
        if [ "${{ inputs.working-directory }}" = '.' ]; then
          echo "cwd=$(pwd)" >> "$GITHUB_OUTPUT"
        else
          echo "cwd=${{ inputs.working-directory }}" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      run: |
        docker run --rm \
          --env "INPUT_PATH=${{ inputs.path }}" \
          --env "INPUT_WORKING_DIRECTORY=${{ steps.check-working-directory.outputs.cwd }}" \
          --volume ${{ github.workspace }}://github/workspace \
          coatl-pip-compile:${{ inputs.python-version }}
