name: coatl-dev-pip-compile-2.7
description: Run pip-compile to upgrade your Python 2 requirements.
author: thecesrom

inputs:
  path:
    description: >-
      A file or location of the requirement file(s).
    required: true
  python-version:
    description: >-
      Python version to use.
    required: true

runs:
  using: docker
  image: '${{ inputs.python-version }}/Dockerfile'
  args:
    - ${{ inputs.path }}
