name: coatl-dev-setup-jython
description: Set up a specific version of Jython and add the command-line tools to the PATH.
author: cesarcoatl

inputs:
  jython-version:
    description: >-
      The Jython version to install.
    required: false
    default: '2.7.3'
  java-distribution:
    description: >-
      Java distribution.
    required: false
    default: 'zulu'
  java-version:
    description: >-
      The Java version to set up.
    required: false
    default: '17'
outputs:
  jython-path:
    description: >-
      The absolute path to the Jython executable.
    value: ${{ steps.get-path.outputs.path }}
  java-distribution:
    description: >-
      Distribution of Java that has been installed.
    value: ${{ steps.get-java-distribution.outputs.java-distribution }}
  java-version:
    description: >-
      Actual version of the java environment that has been installed.
    value: ${{ steps.get-java-version.outputs.java-version }}
  java-path:
    description: >-
      Path to where the java environment has been installed (same as $JAVA_HOME).
    value: ${{ steps.get-java-path.outputs.java-path }}

runs:
  using: composite
  steps:
    - name: Set Jython installation path
      shell: bash
      run: |
        echo "JYTHON_PATH=/opt/jython/${{ inputs.jython-version }}" >> "$GITHUB_ENV"

    - uses: actions/setup-java@v4
      id: setup-java
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Cache Jython
      id: cache-jython
      uses: actions/cache@v4
      with:
        path: ${{ env.JYTHON_PATH }}
        key: jython-${{ inputs.jython-version }}-${{ runner.os }}-${{ steps.setup-java.outputs.distribution }}-${{ steps.setup-java.outputs.version }}

    - name: Install Jython
      if: steps.cache-jython.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q "https://repo1.maven.org/maven2/org/python/jython-installer/${{ inputs.jython-version }}/jython-installer-${{ inputs.jython-version }}.jar"
        java -jar "jython-installer-${{ inputs.jython-version }}.jar" \
          --silent \
          --type standard \
          --directory "$JYTHON_PATH"
        rm -f "jython-installer-${{ inputs.jython-version }}.jar"

    - name: Add Jython to PATH
      shell: bash
      run: |
        echo "$JYTHON_PATH/bin" >> $GITHUB_PATH

    - name: Get absolute path
      id: get-path
      shell: bash
      run: |
        echo "path=$(which jython)" >> "$GITHUB_OUTPUT"

    - name: Set JYTHON_HOME
      shell: bash
      run: |
        echo "JYTHON_HOME=$(dirname $(dirname $(which jython)))" >> "$GITHUB_ENV"

    - name: Get Java distribution
      id: get-java-distribution
      shell: bash
      run: |
        echo "java-distribution=${{ steps.setup-java.outputs.distribution }}" >> "$GITHUB_OUTPUT"

    - name: Get Java path
      id: get-java-path
      shell: bash
      run: |
        echo "java-path=${{ steps.setup-java.outputs.path }}" >> "$GITHUB_OUTPUT"

    - name: Get Java version
      id: get-java-version
      shell: bash
      run: |
        echo "java-version=${{ steps.setup-java.outputs.version }}" >> "$GITHUB_OUTPUT"
