name: coatl-dev-pypi-upload
description: Build and upload Python 2/3 distribution packages.
author: thecesrom

inputs:
  python-version:
    description: >-
      Python version to use for building your distribution packages.
    default: '2.7'
    required: false
  username:
    description: >-
      The username to authenticate to the repository (package index) as.
    required: false
    default: '__token__'
  password:
    description:  >-
      The password to authenticate to the repository (package index) with.
    required: true
  url:
    description: >-
      The repository (package index) URL to upload the package to.
    required: false
    default: 'https://upload.pypi.org/legacy/'
  check:
    description: Check metadata with twine before uploading.
    required: false
    default: 'yes'
  upload:
    description: >-
      Upload automatically.
      Set it to "no" if you would like to upload manually.
    required: false
    default: 'yes'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build ${{ github.action_path }} \
          --build-arg VERSION=${{ inputs.python-version }} \
          --file ${{ github.action_path }}/Dockerfile \
          --tag coatl-dev-pypi-upload:${{ inputs.python-version }}

    - shell: bash
      run: |
        docker run --rm \
          --env "INPUT_USERNAME=${{ inputs.username }}" \
          --env "INPUT_PASSWORD=${{ inputs.password }}" \
          --env "INPUT_URL=${{ inputs.url }}" \
          --env "INPUT_CHECK=${{ inputs.check }}" \
          --env "INPUT_UPLOAD=${{ inputs.upload }}" \
          --volume ${{ github.workspace }}://github/workspace \
          coatl-dev-pypi-upload:${{ inputs.python-version }}
