name: coatl-dev-uv-pip-compile
description: Run uv pip compile to upgrade your Python requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      The location of the requirement file(s).
    required: true
  python-version:
    description: >-
      The version of Python to set UV_PYTHON to.
    required: false
    default: '3.14'
  uv-version:
    description: >-
      The version of uv to install.
    required: false
    default: 'latest'
  working-directory:
    description: >-
      The working directory to run the action in.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
      with:
        enable-cache: 'false'
        python-version: '${{ inputs.python-version }}'
        version: ${{ inputs.uv-version }}

    - name: Install Python ${{ inputs.python-version }}
      shell: bash
      run: |
        uv python install ${INPUTS_PYTHON_VERSION}
      env:
        INPUTS_PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Create Pull Request
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: |
        ${{ github.action_path }}/action.sh
