name: coatl-dev-uv-pip-compile
description: Run uv pip compile to upgrade your Python requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      The location of the requirement file(s).
    required: true
  python-version:
    description: >-
      The version of Python to set UV_PYTHON to.
    required: false
    default: '3.14'
  uv-version:
    description: >-
      The version of uv to install.
    required: false
    default: 'latest'
  working-directory:
    description: >-
      The working directory to run the action in.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        enable-cache: 'false'
        python-version: '${{ inputs.python-version }}'
        version: ${{ inputs.uv-version }}

    - name: Install Python ${{ inputs.python-version }}
      shell: bash
      env:
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        uv python install "${INPUT_PYTHON_VERSION}"

    - name: Create Pull Request
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: |
        action.sh
