name: coatl-dev-pip-compile-3.11
description: Run pip-compile to upgrade your Python 3 requirements.
author: thecesrom

inputs:
  path:
    description: >-
      A file or location of the requirement file(s).
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
