name: coatl-dev-pip-compile-upgrade
description: Run pip-compile to upgrade your Python 2.7 requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      The location of the requirement file(s).
    required: true
  extra-args:
    description: >-
      Extra arguments to pass to pip-compile.
    required: false
    default: ''
  working-directory:
    description: >-
      The working directory to run the action in.
    required: false
    default: '.'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_EXTRA_ARGS: ${{ inputs.extra-args }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
