name: coatl-dev-pip-compile
description: Run pip-compile to upgrade your Python 2/3 requirements.
author: cesarcoatl

inputs:
  path:
    description: >-
      The location of the requirement file(s).
    required: true
  extra-args:
    description: >-
      Extra arguments to pass to pip-compile.
    required: false
    default: ''
  working-directory:
    description: >-
      The working directory to run the action in.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build \
          --build-arg VERSION=${{ inputs.python-version }} \
          --file ${{ github.action_path }}/Dockerfile \
          --tag coatl-dev-pip-compile-upgrade-action \
          ${{ github.action_path }}

    - shell: bash
      run: |
        docker run --rm \
          --env "INPUT_PATH=${{ inputs.path }}" \
          --env "INPUT_USE_CONFIG=${{ inputs.use-config }}" \
          --env "INPUT_CONFIG_FILE=${{ inputs.config-file }}" \
          --env "INPUT_EXTRA_ARGS=${{ inputs.extra-args }}" \
          --env "INPUT_WORKING_DIRECTORY=${{ inputs.working-directory }}" \
          --volume ${{ github.workspace }}://github/workspace \
          coatl-dev-pip-compile-upgrade-action
