name: coatl-dev-pip-compile
description: Run pip-compile to upgrade your Python 2 requirements.
author: thecesrom

inputs:
  path:
    description: >-
      A file ('setup.py' or 'requirements.txt') or location of the requirement files.
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
