name: test-pip-compile-upgrade

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pip-compile-upgrade.yaml'
      - 'pip-compile-upgrade/**'
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: pip-compile-upgrade/test/2.7/requirements
            python-version: '2.7'
            use-config: 'no'
          - path: pip-compile-upgrade/test/3.12/requirements
            python-version: '3.12'
            use-config: 'yes'
          - path: pip-compile-upgrade/test/3.13/requirements
            python-version: '3.13'
            use-config: 'no'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: pip-compile-upgrade
        uses: ./pip-compile-upgrade
        with:
          path: ${{ matrix.path }}
          python-version: ${{ matrix.python-version }}
          use-config: ${{ matrix.use-config }}

      - name: Detect changes
        id: git-diff
        uses: ./simple-git-diff
        with:
          path: ${{ matrix.path }}

      - name: Show output
        run: |
          echo "Changes were detected: ${{ steps.git-diff.outputs.diff }}"
