name: test-pypi-upload

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pypi-upload.yaml'
      - 'pypi-upload/**'
  workflow_dispatch:

env:
  devpi-password: 'changeme'
  devpi-username: 'root'
  devpi-port: '3141'

jobs:
  self-test:
    name: pypi-upload-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    services:
      devpi:
        image: coatldev/devpi:latest
        env:
          DEVPI_PASSWORD: ${{ env.devpi-password }}
        ports:
          - 3141
    strategy:
      matrix:
        python-version: ['2.7', '3.11']
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Switch directories
        run: |
          cd "pypi-upload/test/${{ matrix.python-version }}"

      - name: Test action
        uses: ./pypi-upload
        env:
          DEBUG: true
          PATH: utter-nonsense
        with:
          username: "${{ env.devpi-username }}"
          password: "${{ env.devpi-password }}"
          register: 'yes'
          url: "http://devpi:${{ env.devpi-port }}/${{ env.devpi-username }}/public/"
