name: test-gpg-import

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-gpg-import.yaml'
      - 'gpg-import/**'
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Import GPG
        uses: ./gpg-import
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - name: Show Output
        run: |
          echo "git user.email: ${{ steps.gpg-import.outputs.git-user-email }}"
          echo "git user.name: ${{ steps.gpg-import.outputs.git-user-name }}"
