name: test-pip-compile

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pip-compile.yml'
      - 'pip-compile/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          verbose: true

  self-test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: pip-compile
        uses: ./
        with:
          path: 'pip-compile/requirements'
