name: test-uv-pip-compile-upgrade

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-uv-pip-compile-upgrade.yaml'
      - 'uv-pip-compile-upgrade/**'
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: uv-pip-compile-upgrade/test/requirements

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: uv-pip-compile-upgrade
        uses: ./uv-pip-compile-upgrade
        with:
          path: ${{ env.REQUIREMENTS_PATH }}

      - name: Detect changes
        id: git-diff
        uses: ./simple-git-diff
        with:
          path: ${{ env.REQUIREMENTS_PATH }}

      - name: Show output
        run: |
          echo "Changes were detected: ${{ steps.git-diff.outputs.diff }}"
