name: test-pre-commit-autoupdate

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pre-commit-autoupdate.yaml'
      - 'pre-commit-autoupdate/**'
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update pre-commit hooks
        uses: ./pre-commit-autoupdate
        id: pre-commit-autoupdate
        with:
          pr-create: 'no'

      - name: Show Output
        run: |
          echo "pre-commit updates are present: ${{ steps.pre-commit-autoupdate.outputs.update-hit }}"
