name: test-pip-compile-2.7

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pip-compile-2.7.yaml'
      - 'pip-compile-2.7/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          verbose: true

  self-test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: 'pip-compile-2.7/requirements'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: pip-compile
        uses: ./pip-compile-2.7
        with:
          path: "${{ env.REQUIREMENTS_PATH }}"

      - name: Detect changes
        id: git-diff
        uses: ./simple-git-diff
        with:
          path: "${{ env.REQUIREMENTS_PATH }}"

      - name: Show output
        run: |
          echo "Changes were detected: ${{ steps.git-diff.outputs.diff }}"
