name: test-pip-compile-upgrade

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/test-pip-compile-upgrade.yaml'
      - 'pip-compile-upgrade/**'
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update requirements
        uses: ./pip-compile-upgrade
        id: pip-compile-upgrade
        with:
          path: pip-compile/test/${{ env.PYTHON_VERSION }}/requirements
          python-version: ${{ env.PYTHON_VERSION }}
          pr-create: 'no'

      - name: Show Output
        run: |
          echo "pip-compile upgrades are present: ${{ steps.pip-compile-upgrade.outputs.update-hit }}"
