name: test-pypi-upload

on:
  pull_request:
    branches:
      - coatl
    paths:
      - .github/workflows/test-pypi-upload.yaml
      - pypi-upload/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout coatl-dev/actions repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false


      - name: Checkout test repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ignition-devs/incendium
          path: incendium
          persist-credentials: false

      - name: pypi-upload-2.7
        uses: ./pypi-upload
        with:
          dry-run: true
          working-directory: incendium

      - name: pypi-upload-3.12
        uses: ./pypi-upload
        with:
          dry-run: true
          working-directory: incendium/stubs
          python-version: '3.12'
