name: test-pip-compile-upgrade

on:
  pull_request:
    branches:
      - coatl
    paths:
      - .github/workflows/test-pip-compile-upgrade.yaml
      - pip-compile-upgrade/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  self-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: pip-compile-upgrade/test/2.7/requirements
            working-directory: ${{ github.workspace }}
          - path: tools.txt
            working-directory: pip-compile-upgrade/test/2.7/requirements/tools

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: pip-compile-upgrade
        uses: ./pip-compile-upgrade
        with:
          path: ${{ matrix.path }}
          extra-args: '--dry-run --reuse-hashes --verbose'
          working-directory: ${{ matrix.working-directory }}
