name: test-simple-git-diff

on:
  pull_request:
    branches:
      - coatl
    paths:
      - .github/workflows/test-simple-git-diff.yaml
      - simple-git-diff/**
  workflow_dispatch:

jobs:
  test-true:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false

      - name: Modify file in repo
        run: |
          echo "New line" >> README.md

      - name: Detect changes
        id: git-diff
        uses: ./simple-git-diff
        with:
          path: 'README.md'

      - name: Test true
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          echo "Changes were detected."

  test-false:
    runs-on: ubuntu-slim
    needs: test-true
    steps:
      - name: Checkout repo
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false

      - name: Detect changes
        id: git-diff
        uses: ./simple-git-diff

      - name: Test false
        if: ${{ steps.git-diff.outputs.diff != 'true' }}
        run: |
          echo "Changes were not detected."
