name: test-gpg-import

on:
  pull_request:
    branches:
      - coatl
    paths:
      - .github/workflows/test-gpg-import.yaml
      - gpg-import/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  self-test:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Import GPG
        uses: ./gpg-import
        id: gpg-import
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - name: Show Output
        run: |
          echo "git user.email: ${STEPS_GPG_IMPORT_OUTPUTS_GIT_USER_EMAIL}"
          echo "git user.name: ${STEPS_GPG_IMPORT_OUTPUTS_GIT_USER_NAME}"
        env:
          STEPS_GPG_IMPORT_OUTPUTS_GIT_USER_EMAIL: ${{ steps.gpg-import.outputs.git-user-email }}
          STEPS_GPG_IMPORT_OUTPUTS_GIT_USER_NAME: ${{ steps.gpg-import.outputs.git-user-name }}
